# yaml-language-server: $schema=../../schemas/schemas/preset.schema.json

kind: Preset

metadata:
  name: base

spec:
  marketplaces:
    claude-plugins-official:
      source: { source: github, repo: anthropics/claude-plugins-official }
      autoUpdate: true
      scope: user

  plugins:
    claude-code-setup@claude-plugins-official: { enabled: true, scope: user }
    claude-md-management@claude-plugins-official: { enabled: true, scope: user }    
    skill-creator@claude-plugins-official: { enabled: true, scope: user }
    

  skills:
    # - vercel-labs/skills

  mcpServers:
    